"""empty message

Revision ID: 036b62df80cc
Revises: cbdc988a7df4
Create Date: 2018-02-12 11:39:20.196304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "036b62df80cc"
down_revision = "cbdc988a7df4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("page", sa.Column("review_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("page", "review_token")
    # ### end Alembic commands ###
