"""empty message

Revision ID: 0a5dfd89736c
Revises: 20170227_add_latest_flag_to_page
Create Date: 2018-03-05 14:42:04.312894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5dfd89736c'
down_revision = '20170227_add_latest_flag_to_page'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorisation_value', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorisation_value', 'position')
    # ### end Alembic commands ###
