"""empty message

Revision ID: 0b88fff8fffe
Revises: 99062ef6b9dc
Create Date: 2017-09-29 16:54:19.721241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b88fff8fffe'
down_revision = '99062ef6b9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_dimension', 'disclosure_control')
    op.drop_column('db_dimension', 'location')
    op.drop_column('db_dimension', 'source')
    op.drop_column('db_dimension', 'suppression_rules')
    op.drop_column('db_dimension', 'type_of_statistic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dimension', sa.Column('type_of_statistic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('db_dimension', sa.Column('suppression_rules', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('db_dimension', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('db_dimension', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('db_dimension', sa.Column('disclosure_control', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
