"""empty message

Revision ID: 120c0d4099da
Revises: 1be0f1ffc951
Create Date: 2017-10-20 13:46:43.152561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "120c0d4099da"
down_revision = "1be0f1ffc951"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("action", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="audit_pkey"),
    )
    # ### end Alembic commands ###
