"""empty message

Revision ID: 14b3d3067cb3
Revises: 8d8b8a8a9c0b
Create Date: 2018-02-06 13:34:28.117816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b3d3067cb3'
down_revision = '8d8b8a8a9c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension_category', sa.Column('includes_parents', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimension_category', 'includes_parents')
    # ### end Alembic commands ###
