"""empty message

Revision ID: 1a9cee041761
Revises: ec57bb63c500
Create Date: 2017-07-03 15:13:36.656488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
from application.cms.models import DbPage

revision = '1a9cee041761'
down_revision = 'ec57bb63c500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dimension', sa.Column('position', sa.Integer(), nullable=True))

    session = Session(bind=op.get_bind())

    for page in session.query(DbPage):
        for i, dimension in enumerate(page.dimensions):
            dimension.position = i
        session.add(page)
        session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_dimension', 'position')
    # ### end Alembic commands ###
