"""empty message

Revision ID: 2018_09_24_sync_classification
Revises: 2018_09_18_classifications
Create Date: 2018-09-24 08:45:04.242855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2018_09_24_sync_classification'
down_revision = '2018_09_18_classifications'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind()
    op.execute("""
        DELETE from dimension_categorisation 
        USING categorisation 
        WHERE categorisation.id = dimension_categorisation.categorisation_id AND categorisation.code = '19A';
        DELETE from association
        USING categorisation 
        WHERE categorisation.id = association.categorisation_id AND categorisation.code = '19A';
        DELETE from parent_association
        USING categorisation 
        WHERE categorisation.id = parent_association.categorisation_id AND categorisation.code = '19A';
        DELETE from categorisation 
        WHERE categorisation.code = '19A';
        
        DELETE from dimension_categorisation 
        USING categorisation 
        WHERE categorisation.id = dimension_categorisation.categorisation_id AND categorisation.code = '5D';
        DELETE from association
        USING categorisation 
        WHERE categorisation.id = association.categorisation_id AND categorisation.code = '5D';
        DELETE from parent_association
        USING categorisation 
        WHERE categorisation.id = parent_association.categorisation_id AND categorisation.code = '5D';
        DELETE from categorisation 
        WHERE categorisation.code = '5D';
        
        DELETE from dimension_categorisation 
        USING categorisation 
        WHERE categorisation.id = dimension_categorisation.categorisation_id AND categorisation.code = '11A';
        DELETE from association
        USING categorisation 
        WHERE categorisation.id = association.categorisation_id AND categorisation.code = '11A';
        DELETE from parent_association
        USING categorisation 
        WHERE categorisation.id = parent_association.categorisation_id AND categorisation.code = '11A';
        DELETE from categorisation 
        WHERE categorisation.code = '11A';
        
        UPDATE categorisation SET code = '11A' WHERE code = '12A';
    """)

    # ### end Alembic commands ###


def downgrade():
    # No way to undo this!
    pass
    # ### end Alembic commands ###
