"""empty message

Revision ID: 93ed2652f6f5
Revises: 2018_05_14_share_pages
Create Date: 2018-06-07 16:00:02.484106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2018_06_08_chartbuilder_2'
down_revision = '2018_06_15_rebase_migration'

branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension', sa.Column('chart_2_source_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('dimension', sa.Column('chart_source', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimension', 'chart_source')
    op.drop_column('dimension', 'chart_2_source_data')
    # ### end Alembic commands ###
