"""empty message

Revision ID: 2018_04_20_data_src_refactor
Revises: 2018_04_11_add_sandbox_topic
Create Date: 2018-04-20 13:03:32.478880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ARRAY

revision = "2018_04_20_data_src_refactor"
down_revision = "2018_04_11_add_sandbox_topic"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    type_of_data_types = sa.Enum("ADMINISTRATIVE", "SURVEY", name="type_of_data_types")
    op.add_column("page", sa.Column("secondary_source_1_type_of_data", ARRAY(type_of_data_types), nullable=True))
    op.add_column("page", sa.Column("suppression_and_disclosure", sa.TEXT(), nullable=True))
    op.add_column("page", sa.Column("note_on_corrections_or_updates", sa.TEXT(), nullable=True))
    op.add_column("page", sa.Column("secondary_source_1_note_on_corrections_or_updates", sa.TEXT(), nullable=True))
    op.add_column("page", sa.Column("secondary_source_1_data_source_purpose", sa.TEXT(), nullable=True))

    op.get_bind()

    op.execute(
        """
        UPDATE page SET suppression_and_disclosure = suppression_rules
        WHERE disclosure_control is null;
    """
    )

    op.execute(
        """
           UPDATE page SET suppression_and_disclosure = disclosure_control
           WHERE suppression_rules is null;
       """
    )

    op.execute(
        """
        UPDATE page SET suppression_and_disclosure = trim(suppression_rules  || '  ' ||  disclosure_control)
        WHERE suppression_rules is not null
        AND  disclosure_control is not null;
    """
    )

    op.drop_constraint("organisation_secondary_source_2_fkey", "page", type_="foreignkey")
    op.drop_constraint("frequency_secondary_source_2_fkey", "page", type_="foreignkey")
    op.drop_constraint("secondary_source_2_type_of_statistic_fkey", "page", type_="foreignkey")
    op.drop_column("page", "secondary_source_1_date_next_update")
    op.drop_column("page", "secondary_source_1_date_updated")
    op.drop_column("page", "secondary_source_1_suppression_rules")
    op.drop_column("page", "secondary_source_1_disclosure_control")
    op.drop_column("page", "secondary_source_2_frequency")
    op.drop_column("page", "secondary_source_2_contact_2_name")
    op.drop_column("page", "secondary_source_2_contact_2_phone")
    op.drop_column("page", "secondary_source_2_url")
    op.drop_column("page", "secondary_source_2_date_next_update")
    op.drop_column("page", "secondary_source_2_contact_1_name")
    op.drop_column("page", "last_update_date")
    op.drop_column("page", "secondary_source_2_contact_1_phone")
    op.drop_column("page", "secondary_source_2_publisher_text")
    op.drop_column("page", "secondary_source_2_disclosure_control")
    op.drop_column("page", "secondary_source_2_type_of_statistic_id")
    op.drop_column("page", "secondary_source_2_suppression_rules")
    op.drop_column("page", "secondary_source_2_frequency_other")
    op.drop_column("page", "secondary_source_2_publisher_id")
    op.drop_column("page", "secondary_source_2_title")
    op.drop_column("page", "secondary_source_2_date")
    op.drop_column("page", "next_update_date")
    op.drop_column("page", "secondary_source_2_date_updated")
    op.drop_column("page", "secondary_source_2_statistic_type")
    op.drop_column("page", "secondary_source_2_frequency_id")
    op.drop_column("page", "secondary_source_2_contact_2_email")
    op.drop_column("page", "secondary_source_2_contact_1_email")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "page", sa.Column("secondary_source_2_contact_1_email", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "page", sa.Column("secondary_source_2_contact_2_email", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "page", sa.Column("secondary_source_2_frequency_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column("page", sa.Column("secondary_source_2_statistic_type", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("page", sa.Column("secondary_source_2_date_updated", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("page", sa.Column("secondary_source_2_date", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("page", sa.Column("secondary_source_2_title", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "page", sa.Column("secondary_source_2_publisher_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.add_column(
        "page",
        sa.Column("secondary_source_2_frequency_other", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "page", sa.Column("secondary_source_2_suppression_rules", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "page", sa.Column("secondary_source_2_type_of_statistic_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "page", sa.Column("secondary_source_2_disclosure_control", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("page", sa.Column("secondary_source_2_publisher_text", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "page", sa.Column("secondary_source_2_contact_1_phone", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("page", sa.Column("secondary_source_2_contact_1_name", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "page", sa.Column("secondary_source_2_date_next_update", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("page", sa.Column("secondary_source_2_url", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "page", sa.Column("secondary_source_2_contact_2_phone", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("page", sa.Column("secondary_source_2_contact_2_name", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("page", sa.Column("secondary_source_2_frequency", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("page", sa.Column("last_update_date", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column("page", sa.Column("next_update_date", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(
        "page", sa.Column("secondary_source_1_date_next_update", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column("page", sa.Column("secondary_source_1_date_updated", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "page", sa.Column("secondary_source_1_disclosure_control", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "page", sa.Column("secondary_source_1_suppression_rules", sa.TEXT(), autoincrement=False, nullable=True)
    )

    op.create_foreign_key(
        "secondary_source_2_type_of_statistic_fkey",
        "page",
        "type_of_statistic",
        ["secondary_source_2_type_of_statistic_id"],
        ["id"],
    )
    op.create_foreign_key(
        "frequency_secondary_source_2_fkey", "page", "frequency_of_release", ["secondary_source_2_frequency_id"], ["id"]
    )
    op.create_foreign_key(
        "organisation_secondary_source_2_fkey", "page", "organisation", ["secondary_source_2_publisher_id"], ["id"]
    )

    op.drop_column("page", "secondary_source_1_type_of_data")
    op.drop_column("page", "suppression_and_disclosure")
    op.drop_column("page", "note_on_corrections_or_updates")
    op.drop_column("page", "secondary_source_1_note_on_corrections_or_updates")
    op.drop_column("page", "secondary_source_1_data_source_purpose")

    # ### end Alembic commands ###
