"""empty message

Revision ID: 2018_07_28_redirects
Revises: 2018_06_27_chartbuilder_2
Create Date: 2018-07-27 14:07:32.144075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2018_07_28_redirects"
down_revision = "2018_06_27_chartbuilder_2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "redirect",
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("from_uri", sa.String(length=255), nullable=False),
        sa.Column("to_uri", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("from_uri"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("redirect")
    # ### end Alembic commands ###
