""" add columns for chart-builder 2

Revision ID: 2018_06_27_chartbuilder_2
Revises: 2018_07_03_del_dept_source_text
Create Date: 2018-06-27 14:19:25.607430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2018_06_27_chartbuilder_2'
down_revision = '2018_07_03_del_dept_source_text'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension', sa.Column('chart_2_source_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('dimension', sa.Column('chart_builder_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimension', 'chart_builder_version')
    op.drop_column('dimension', 'chart_2_source_data')
    # ### end Alembic commands ###
