"""empty message

Revision ID: 2018_03_20_remove_unused_fields
Revises: 20180305_add_category_value_pos
Create Date: 2018-03-20 11:25:22.148398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2018_03_20_remove_unused_fields"
down_revision = "20180305_add_category_value_pos"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("page", "geographic_coverage")
    op.drop_column("page", "lowest_level_of_geography_text")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("page", sa.Column("lowest_level_of_geography_text", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("page", sa.Column("geographic_coverage", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
