"""empty message

Revision ID: 2018_09_18_classifications
Revises: 2018_08_12_tablebuilder_2
Create Date: 2018-09-18 14:02:04.242855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2018_09_18_classifications'
down_revision = '2018_08_12_tablebuilder_2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dimension_categorisation', sa.Column('chart_categorisation_id', sa.Integer(), nullable=True))
    op.add_column('dimension_categorisation', sa.Column('chart_includes_all', sa.Boolean(), nullable=True))
    op.add_column('dimension_categorisation', sa.Column('chart_includes_parents', sa.Boolean(), nullable=True))
    op.add_column('dimension_categorisation', sa.Column('chart_includes_unknown', sa.Boolean(), nullable=True))
    op.add_column('dimension_categorisation', sa.Column('table_categorisation_id', sa.Integer(), nullable=True))
    op.add_column('dimension_categorisation', sa.Column('table_includes_all', sa.Boolean(), nullable=True))
    op.add_column('dimension_categorisation', sa.Column('table_includes_parents', sa.Boolean(), nullable=True))
    op.add_column('dimension_categorisation', sa.Column('table_includes_unknown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dimension_categorisation', 'table_includes_unknown')
    op.drop_column('dimension_categorisation', 'table_includes_parents')
    op.drop_column('dimension_categorisation', 'table_includes_all')
    op.drop_column('dimension_categorisation', 'table_categorisation_id')
    op.drop_column('dimension_categorisation', 'chart_includes_unknown')
    op.drop_column('dimension_categorisation', 'chart_includes_parents')
    op.drop_column('dimension_categorisation', 'chart_includes_all')
    op.drop_column('dimension_categorisation', 'chart_categorisation_id')
    # ### end Alembic commands ###
