"""empty message

Revision ID: 25ee89f09e2f
Revises: c6d8e5e1007e
Create Date: 2017-06-22 11:06:33.372998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ee89f09e2f'
down_revision = 'c6d8e5e1007e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_page', sa.Column('published', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_page', 'published')
    # ### end Alembic commands ###
