"""empty message

Revision ID: 29c44838e6b9
Revises: 6ec31fd4ac57
Create Date: 2018-02-16 12:56:01.604148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c44838e6b9'
down_revision = '6ec31fd4ac57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'code')
    # ### end Alembic commands ###
