"""empty message

Revision ID: 2c6aab556fef
Revises: 9e714cde1fe0
Create Date: 2017-07-12 10:55:35.780994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6aab556fef'
down_revision = '9e714cde1fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_upload', sa.Column('size', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_upload', 'size')
    # ### end Alembic commands ###
