"""empty message

Revision ID: 334faaf60a3d
Revises: 76780c17910a
Create Date: 2017-06-26 13:40:18.126157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334faaf60a3d'
down_revision = '76780c17910a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_dimension', 'measure',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_dimension', 'measure',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
