"""empty message

Revision ID: 37bdbcac8251
Revises: 0c148005cc7b
Create Date: 2018-01-16 10:27:02.083788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "37bdbcac8251"
down_revision = "0c148005cc7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    type_of_data_types = sa.Enum("ADMINISTRATIVE", "SURVEY", name="type_of_data_types")
    type_of_data_types.create(op.get_bind())

    op.add_column("page", sa.Column("type_of_data", postgresql.ARRAY(type_of_data_types), nullable=True))

    op.get_bind()
    op.execute(
        """UPDATE page SET type_of_data = '{"ADMINISTRATIVE","SURVEY"}'
                  WHERE data_type ilike '%admin%'
                  AND(data_type ilike '%survey%'
                  OR data_type ilike '%census%');
                  """
    )

    op.execute(
        """UPDATE page SET type_of_data = '{"ADMINISTRATIVE"}'
                  WHERE data_type ilike '%admin%'
                  AND NOT(data_type ilike '%survey%' OR data_type ilike '%census%');
                  """
    )

    op.execute(
        """UPDATE page SET type_of_data = '{"SURVEY"}'
                  WHERE data_type
                  NOT ilike '%admin%'
                  AND(data_type ilike '%survey%' OR data_type ilike '%census%');
                  """
    )

    op.drop_column("page", "data_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("page", sa.Column("data_type", sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.get_bind()
    op.execute(
        """UPDATE page SET data_type = 'Administrative and Survey (including census)'
                  WHERE type_of_data = '{"ADMINISTRATIVE","SURVEY"}';
              """
    )

    op.execute(
        """UPDATE page SET data_type = 'Administrative'
                  WHERE type_of_data = '{"ADMINISTRATIVE"}'
              """
    )

    op.execute(
        """UPDATE page SET data_type = 'Survey (including census)'
                  WHERE type_of_data = '{"SURVEY"}'
              """
    )

    op.drop_column("page", "type_of_data")
    op.execute("DROP TYPE type_of_data_types")
    # ### end Alembic commands ###
