"""empty message

Revision ID: 3a7638c00962
Revises: eaff27489153
Create Date: 2017-06-14 13:08:23.586869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a7638c00962'
down_revision = 'eaff27489153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_page',
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('page_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('parent_guid', sa.String(length=255), nullable=True),
    sa.Column('page_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_guid'], ['db_page.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO snag any table data first
    op.drop_table('db_page')
    # ### end Alembic commands ###
