"""empty message

Revision ID: 419108de3b3d
Revises: 5382560efddb
Create Date: 2017-08-24 14:11:13.151318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "419108de3b3d"
down_revision = "5382560efddb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("db_page", sa.Column("secondary_source_1_contact_1_email", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_contact_1_name", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_contact_1_phone", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_contact_2_email", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_contact_2_name", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_contact_2_phone", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_date", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_date_next_update", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_date_updated", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_disclosure_control", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_frequency", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_publisher", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_statistic_type", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_suppression_rules", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_title", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_1_url", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_contact_1_email", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_contact_1_name", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_contact_1_phone", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_contact_2_email", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_contact_2_name", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_contact_2_phone", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_date", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_date_next_update", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_date_updated", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_disclosure_control", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_frequency", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_publisher", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_statistic_type", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_suppression_rules", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_title", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("secondary_source_2_url", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("db_page", "secondary_source_2_url")
    op.drop_column("db_page", "secondary_source_2_title")
    op.drop_column("db_page", "secondary_source_2_suppression_rules")
    op.drop_column("db_page", "secondary_source_2_statistic_type")
    op.drop_column("db_page", "secondary_source_2_publisher")
    op.drop_column("db_page", "secondary_source_2_frequency")
    op.drop_column("db_page", "secondary_source_2_disclosure_control")
    op.drop_column("db_page", "secondary_source_2_date_updated")
    op.drop_column("db_page", "secondary_source_2_date_next_update")
    op.drop_column("db_page", "secondary_source_2_date")
    op.drop_column("db_page", "secondary_source_2_contact_2_phone")
    op.drop_column("db_page", "secondary_source_2_contact_2_name")
    op.drop_column("db_page", "secondary_source_2_contact_2_email")
    op.drop_column("db_page", "secondary_source_2_contact_1_phone")
    op.drop_column("db_page", "secondary_source_2_contact_1_name")
    op.drop_column("db_page", "secondary_source_2_contact_1_email")
    op.drop_column("db_page", "secondary_source_1_url")
    op.drop_column("db_page", "secondary_source_1_title")
    op.drop_column("db_page", "secondary_source_1_suppression_rules")
    op.drop_column("db_page", "secondary_source_1_statistic_type")
    op.drop_column("db_page", "secondary_source_1_publisher")
    op.drop_column("db_page", "secondary_source_1_frequency")
    op.drop_column("db_page", "secondary_source_1_disclosure_control")
    op.drop_column("db_page", "secondary_source_1_date_updated")
    op.drop_column("db_page", "secondary_source_1_date_next_update")
    op.drop_column("db_page", "secondary_source_1_date")
    op.drop_column("db_page", "secondary_source_1_contact_2_phone")
    op.drop_column("db_page", "secondary_source_1_contact_2_name")
    op.drop_column("db_page", "secondary_source_1_contact_2_email")
    op.drop_column("db_page", "secondary_source_1_contact_1_phone")
    op.drop_column("db_page", "secondary_source_1_contact_1_name")
    op.drop_column("db_page", "secondary_source_1_contact_1_email")
    # ### end Alembic commands ###
