"""empty message

Revision ID: 4244e1e8d347
Revises: 04625e2d6e60
Create Date: 2017-07-31 13:31:41.846687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4244e1e8d347"
down_revision = "04625e2d6e60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("db_page", sa.Column("external_edit_summary", sa.TEXT(), nullable=True))
    op.add_column("db_page", sa.Column("internal_edit_summary", sa.TEXT(), nullable=True))
    op.drop_constraint("uix_db_page_guid_version", "db_page", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_db_page_guid_version", "db_page", ["guid", "version"])
    op.drop_column("db_page", "internal_edit_summary")
    op.drop_column("db_page", "external_edit_summary")
    # ### end Alembic commands ###
