"""empty message

Revision ID: 619cc90bd37e
Revises: 29c44838e6b9
Create Date: 2018-02-20 12:59:11.255225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619cc90bd37e'
down_revision = '29c44838e6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('subfamily', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorisation_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension_categorisation',
    sa.Column('dimension_guid', sa.String(length=255), nullable=False),
    sa.Column('categorisation_id', sa.Integer(), nullable=False),
    sa.Column('includes_parents', sa.Boolean(), nullable=True),
    sa.Column('includes_all', sa.Boolean(), nullable=True),
    sa.Column('includes_unknown', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categorisation_id'], ['categorisation.id'], ),
    sa.ForeignKeyConstraint(['dimension_guid'], ['dimension.guid'], ),
    sa.PrimaryKeyConstraint('dimension_guid', 'categorisation_id')
    )

    op.add_column('association', sa.Column('categorisation_id', sa.Integer(), nullable=True))
    op.add_column('association', sa.Column('categorisation_value_id', sa.Integer(), nullable=True))
    op.drop_constraint('association_category_value_id_fkey', 'association', type_='foreignkey')
    op.drop_constraint('association_category_id_fkey', 'association', type_='foreignkey')
    op.create_foreign_key(None, 'association', 'categorisation_value', ['categorisation_value_id'], ['id'])
    op.create_foreign_key(None, 'association', 'categorisation', ['categorisation_id'], ['id'])
    op.drop_column('association', 'category_id')
    op.drop_column('association', 'category_value_id')
    op.add_column('parent_association', sa.Column('categorisation_id', sa.Integer(), nullable=True))
    op.add_column('parent_association', sa.Column('categorisation_value_id', sa.Integer(), nullable=True))
    op.drop_constraint('parent_association_category_value_id_fkey', 'parent_association', type_='foreignkey')
    op.drop_constraint('parent_association_category_id_fkey', 'parent_association', type_='foreignkey')
    op.create_foreign_key(None, 'parent_association', 'categorisation', ['categorisation_id'], ['id'])
    op.create_foreign_key(None, 'parent_association', 'categorisation_value', ['categorisation_value_id'], ['id'])
    op.drop_column('parent_association', 'category_id')
    op.drop_column('parent_association', 'category_value_id')
    op.drop_table('dimension_category')
    op.drop_table('category_value')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_association', sa.Column('category_value_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parent_association', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parent_association', type_='foreignkey')
    op.drop_constraint(None, 'parent_association', type_='foreignkey')
    op.create_foreign_key('parent_association_category_id_fkey', 'parent_association', 'category', ['category_id'], ['id'])
    op.create_foreign_key('parent_association_category_value_id_fkey', 'parent_association', 'category_value', ['category_value_id'], ['id'])
    op.drop_column('parent_association', 'categorisation_value_id')
    op.drop_column('parent_association', 'categorisation_id')
    op.add_column('association', sa.Column('category_value_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('association', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.drop_constraint(None, 'association', type_='foreignkey')
    op.create_foreign_key('association_category_id_fkey', 'association', 'category', ['category_id'], ['id'])
    op.create_foreign_key('association_category_value_id_fkey', 'association', 'category_value', ['category_value_id'], ['id'])
    op.drop_column('association', 'categorisation_value_id')
    op.drop_column('association', 'categorisation_id')
    op.create_table('category_value',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_value_pkey')
    )
    op.create_table('dimension_category',
    sa.Column('dimension_guid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('includes_parents', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('includes_all', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('includes_unknown', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='dimension_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['dimension_guid'], ['dimension.guid'], name='dimension_category_dimension_guid_fkey'),
    sa.PrimaryKeyConstraint('dimension_guid', 'category_id', name='dimension_category_pkey')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subfamily', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('family', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    op.drop_table('dimension_categorisation')
    op.drop_table('categorisation_value')
    op.drop_table('categorisation')
    # ### end Alembic commands ###
