"""empty message

Revision ID: 6c3fde4280e0
Revises: 14b3d3067cb3
Create Date: 2018-02-09 13:11:11.377132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3fde4280e0'
down_revision = '14b3d3067cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_category',
    sa.Column('dimension_guid', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('includes_parents', sa.Boolean(), nullable=True),
    sa.Column('includes_all', sa.Boolean(), nullable=True),
    sa.Column('includes_unknown', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['dimension_guid'], ['dimension.guid'], ),
    sa.PrimaryKeyConstraint('dimension_guid', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dimension_category')
    # ### end Alembic commands ###
