"""empty message

Revision ID: 6ec31fd4ac57
Revises: 8d8b8a8a9c0b
Create Date: 2018-02-13 10:40:31.461975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec31fd4ac57'
down_revision = '8d8b8a8a9c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_association',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_value_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['category_value_id'], ['category_value.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_association')
    # ### end Alembic commands ###
