"""empty message

Revision ID: 6fa486580023
Revises: addb446d684c
Create Date: 2018-02-05 11:50:03.596378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fa486580023"
down_revision = "addb446d684c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lowest_level_of_geography",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )

    op.alter_column(
        "page", "lowest_level_of_geography", nullable=True, new_column_name="lowest_level_of_geography_text"
    )

    op.add_column("page", sa.Column("lowest_level_of_geography_id", sa.String(length=255), nullable=True))
    op.create_foreign_key(
        "page_lowest_level_of_geography_fkey",
        "page",
        "lowest_level_of_geography",
        ["lowest_level_of_geography_id"],
        ["name"],
    )

    op.get_bind()
    op.execute(
        """
        INSERT INTO lowest_level_of_geography (name, position) VALUES ('United Kingdom', 1);
        INSERT INTO lowest_level_of_geography (name, description, position) VALUES ('Country', '(e.g. England, England and Wales, Scotland...)', 2);
        INSERT INTO lowest_level_of_geography (name, description, position) VALUES ('Region', '(e.g. South West, London, North West, Wales...)', 3);
        INSERT INTO lowest_level_of_geography (name, description, position) VALUES ('Local authority upper', '(e.g. County councils and unitary authorities)', 4);
        INSERT INTO lowest_level_of_geography (name, description, position) VALUES ('Local authority lower', '(e.g. District councils and unitary authorities)', 5);
        INSERT INTO lowest_level_of_geography (name, position) VALUES ('Police force area', 6);
        INSERT INTO lowest_level_of_geography (name, position) VALUES ('Clinical commissioning group', 7);
    """
    )

    op.execute(
        """
        UPDATE page SET lowest_level_of_geography_id = 'United Kingdom' WHERE lowest_level_of_geography_text IN ('United Kingdom', 'National');
        UPDATE page SET lowest_level_of_geography_id = 'Country' WHERE lowest_level_of_geography_text = 'England';
        UPDATE page SET lowest_level_of_geography_id = 'Region' WHERE lowest_level_of_geography_text IN ('Regional', 'Region', 'Regions');
        UPDATE page SET lowest_level_of_geography_id = 'Police force area' WHERE lowest_level_of_geography_text IN ('Police force area', 'Police Force Area');
    """
    )

    op.execute(
        """
        UPDATE page SET lowest_level_of_geography_id = 'Local authority upper'
        WHERE guid in ('054_DfE', '056_DfE', '58', 'Dfe_001', 'DfE002', 'DfE005', 'DfE006', 'DfE007',
        'DfE008', 'DfE013', 'DfE014', 'DfE015', 'DfE016', 'DfE017', 'Dfe_029', 'Dfe_030', 'Dfe_031', 'Dfe_032',
        'Dfe_033', 'DH 041', 'DH_042', 'DH_043', 'DH_044', 'DH_045', 'DH_046', 'DH_047', 'DH_048', 'DH_049');
    """
    )

    op.execute(
        """
        UPDATE page SET lowest_level_of_geography_id = 'Local authority lower'
        WHERE guid in ('DWP 001','DWP 002', 'DWP 003', 'DCLG 017', 'DCLG 018');
    """
    )

    op.execute(
        """
        UPDATE page SET lowest_level_of_geography_id = 'Region'
        WHERE guid = 'DWP 011';
    """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("page_lowest_level_of_geography_fkey", "page", type_="foreignkey")
    op.drop_column("page", "lowest_level_of_geography_id")
    op.drop_table("lowest_level_of_geography")
    op.alter_column(
        "page", "lowest_level_of_geography_text", nullable=True, new_column_name="lowest_level_of_geography"
    )
    # ### end Alembic commands ###
