"""empty message

Revision ID: 719c68424583
Revises: 01b5b95b092d
Create Date: 2018-02-21 11:09:15.230546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "719c68424583"
down_revision = "01b5b95b092d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorisation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("family", sa.String(length=255), nullable=True),
        sa.Column("subfamily", sa.String(length=255), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categorisation_value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "association",
        sa.Column("categorisation_id", sa.Integer(), nullable=True),
        sa.Column("categorisation_value_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["categorisation_id"], ["categorisation.id"], name="categorisation_association_fkey"),
        sa.ForeignKeyConstraint(
            ["categorisation_value_id"], ["categorisation_value.id"], name="categorisation_value_association_fkey"
        ),
    )
    op.create_table(
        "parent_association",
        sa.Column("categorisation_id", sa.Integer(), nullable=True),
        sa.Column("categorisation_value_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["categorisation_id"], ["categorisation.id"], name="categorisation_parent_association_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["categorisation_value_id"],
            ["categorisation_value.id"],
            name="categorisation_value_parent_association_fkey",
        ),
    )
    op.create_table(
        "dimension_categorisation",
        sa.Column("dimension_guid", sa.String(length=255), nullable=False),
        sa.Column("categorisation_id", sa.Integer(), nullable=False),
        sa.Column("includes_parents", sa.Boolean(), nullable=True),
        sa.Column("includes_all", sa.Boolean(), nullable=True),
        sa.Column("includes_unknown", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["categorisation_id"], ["categorisation.id"], name="categorisation_dimension_categorisation_fkey"
        ),
        sa.ForeignKeyConstraint(["dimension_guid"], ["dimension.guid"], name="dimension_dimension_categorisation_fkey"),
        sa.PrimaryKeyConstraint("dimension_guid", "categorisation_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dimension_categorisation")
    op.drop_table("parent_association")
    op.drop_table("association")
    op.drop_table("categorisation_value")
    op.drop_table("categorisation")
    # ### end Alembic commands ###
