"""empty message

Revision ID: 7480ee96ed95
Revises: 0b88fff8fffe
Create Date: 2017-09-29 16:54:36.682903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

from application.cms.models import DbPage

revision = '7480ee96ed95'
down_revision = '0b88fff8fffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('db_upload_page_id_version_fkey', 'db_upload', type_='foreignkey')
    op.drop_constraint('db_dimension_measure_id_version_fkey', 'db_dimension', type_='foreignkey')
    op.drop_constraint('db_page_parent_guid_version_fkey', 'db_page', type_='foreignkey')
    # op.drop_constraint('uix_db_page_guid_version', 'db_page', type_='unique')
    op.drop_constraint('db_page_guid_version_pkey', 'db_page', type_='primary')

    session = Session(bind=op.get_bind())

    page = session.query(DbPage).filter_by(guid='topic_work').one()
    page.guid = 'topic_workpayandbenefits'
    page.uri = 'work-pay-and-benefits'
    page.title = 'Work, pay and benefits'

    for p in session.query(DbPage).filter_by(parent_guid='topic_work'):
        p.parent_guid = 'topic_workpayandbenefits'
        session.add(p)

    session.add(page)
    session.commit()

    page = session.query(DbPage).filter_by(guid='topic_education').one()
    page.guid = 'topic_educationskillsandtraining'
    page.uri = 'education-skills-and-training'
    page.title = 'Education, skills and training'

    for p in session.query(DbPage).filter_by(parent_guid='topic_education'):
        p.parent_guid = 'topic_educationskillsandtraining'
        session.add(p)

    session.add(page)
    session.commit()

    page = session.query(DbPage).filter_by(guid='topic_housingandlivingstandards').one()
    page.guid = 'topic_housing'
    page.uri = 'housing'
    page.title = 'Housing'

    for p in session.query(DbPage).filter_by(parent_guid='topic_housingandlivingstandards'):
        p.parent_guid = 'topic_housing'
        session.add(p)

    session.add(page)
    session.commit()

    op.create_primary_key('db_page_guid_version_pkey', 'db_page', ['guid', 'version'])
    op.create_unique_constraint('uix_db_page_guid_version', 'db_page', ['guid', 'version'])
    op.create_foreign_key('db_dimension_measure_id_version_fkey', 'db_dimension', 'db_page',
                          ['measure_id', 'measure_version'], ['guid', 'version'])
    op.create_foreign_key('db_upload_page_id_version_fkey', 'db_upload', 'db_page', ['page_id', 'page_version'],
                          ['guid', 'version'])
    op.create_foreign_key('db_page_parent_guid_version_fkey', 'db_page', 'db_page', ['parent_guid', 'parent_version'],
                          ['guid', 'version'])



    # ### end Alembic commands ###


def downgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('db_upload_page_id_version_fkey', 'db_upload', type_='foreignkey')
    op.drop_constraint('db_dimension_measure_id_version_fkey', 'db_dimension', type_='foreignkey')
    op.drop_constraint('db_page_parent_guid_version_fkey', 'db_page', type_='foreignkey')
    op.drop_constraint('db_page_guid_version_pkey', 'db_page', type_='primary')
    # op.drop_constraint('uix_db_page_guid_version', 'db_page', type_='unique')

    session = Session(bind=op.get_bind())

    page = session.query(DbPage).filter_by(guid='topic_workpayandbenefits').one()
    page.guid = 'topic_work'
    page.uri = 'work'
    page.title = 'Work'

    for p in session.query(DbPage).filter_by(parent_guid='topic_workpayandbenefits'):
        p.parent_guid = 'topic_work'
        session.add(p)

    session.add(page)
    session.commit()

    page = session.query(DbPage).filter_by(guid='topic_educationskillsandtraining').one()
    page.guid = 'topic_education'
    page.uri = 'education'
    page.title = 'Education'

    for p in session.query(DbPage).filter_by(parent_guid='topic_educationskillsandtraining'):
        p.parent_guid = 'topic_education'
        session.add(p)

    session.add(page)
    session.commit()

    page = session.query(DbPage).filter_by(guid='topic_housing').one()
    page.guid = 'topic_housingandlivingstandards'
    page.uri = 'housing-and-living-standards'
    page.title = 'Housing and living standards'

    for p in session.query(DbPage).filter_by(parent_guid='topic_housing'):
        p.parent_guid = 'topic_housingandlivingstandards'
        session.add(p)

    session.add(page)
    session.commit()

    op.create_primary_key('db_page_guid_version_pkey', 'db_page', ['guid', 'version'])
    op.create_unique_constraint('uix_db_page_guid_version', 'db_page', ['guid', 'version'])
    op.create_foreign_key('db_dimension_measure_id_version_fkey', 'db_dimension', 'db_page',
                          ['measure_id', 'measure_version'], ['guid', 'version'])
    op.create_foreign_key('db_upload_page_id_version_fkey', 'db_upload', 'db_page', ['page_id', 'page_version'],
                          ['guid', 'version'])
    op.create_foreign_key('db_page_parent_guid_version_fkey', 'db_page', 'db_page', ['parent_guid', 'parent_version'],
                          ['guid', 'version'])

    # ### end Alembic commands ###