"""empty message

Revision ID: 76780c17910a
Revises: 8b0d42432172
Create Date: 2017-06-26 13:38:01.360076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76780c17910a'
down_revision = '8b0d42432172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dimension', sa.Column('measure', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'db_dimension', 'db_page', ['measure'], ['guid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'db_dimension', type_='foreignkey')
    op.drop_column('db_dimension', 'measure')
    # ### end Alembic commands ###
