"""empty message

Revision ID: 8b0d42432172
Revises: a6d57f7d9ef0
Create Date: 2017-06-26 12:27:33.881538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0d42432172'
down_revision = 'a6d57f7d9ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dimension', sa.Column('chart_source_data', sa.Text(), nullable=True))
    op.add_column('db_dimension', sa.Column('table_source_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_dimension', 'table_source_data')
    op.drop_column('db_dimension', 'chart_source_data')
    # ### end Alembic commands ###
