"""empty message

Revision ID: 8c3ea028a8c5
Revises: 4fb14b219852
Create Date: 2017-06-30 12:57:39.154467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.

revision = '8c3ea028a8c5'
down_revision = '4fb14b219852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_page', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('contact_phone', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('data_source_purpose', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('data_type', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('department_source', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('disclosure_control', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('estimation', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('ethnicity_definition_detail', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('ethnicity_definition_summary', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('frequency', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('further_technical_information', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('geographic_coverage', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('last_update_date', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('lowest_level_of_geography', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('measure_summary', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('methodology', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('need_to_know', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('next_update_date', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('published_date', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('qmi_url', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('related_publications', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('source_text', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('source_url', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('subtopics', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('db_page', sa.Column('summary', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('suppression_rules', sa.TEXT(), nullable=True))
    op.add_column('db_page', sa.Column('time_covered', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('db_page', sa.Column('type_of_statistic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_page', 'type_of_statistic')
    op.drop_column('db_page', 'title')
    op.drop_column('db_page', 'time_covered')
    op.drop_column('db_page', 'suppression_rules')
    op.drop_column('db_page', 'summary')
    op.drop_column('db_page', 'subtopics')
    op.drop_column('db_page', 'source_url')
    op.drop_column('db_page', 'source_text')
    op.drop_column('db_page', 'related_publications')
    op.drop_column('db_page', 'qmi_url')
    op.drop_column('db_page', 'published_date')
    op.drop_column('db_page', 'next_update_date')
    op.drop_column('db_page', 'need_to_know')
    op.drop_column('db_page', 'methodology')
    op.drop_column('db_page', 'measure_summary')
    op.drop_column('db_page', 'lowest_level_of_geography')
    op.drop_column('db_page', 'last_update_date')
    op.drop_column('db_page', 'geographic_coverage')
    op.drop_column('db_page', 'further_technical_information')
    op.drop_column('db_page', 'frequency')
    op.drop_column('db_page', 'ethnicity_definition_summary')
    op.drop_column('db_page', 'ethnicity_definition_detail')
    op.drop_column('db_page', 'estimation')
    op.drop_column('db_page', 'disclosure_control')
    op.drop_column('db_page', 'department_source')
    op.drop_column('db_page', 'data_type')
    op.drop_column('db_page', 'data_source_purpose')
    op.drop_column('db_page', 'contact_phone')
    op.drop_column('db_page', 'contact_name')
    op.drop_column('db_page', 'contact_email')
    # ### end Alembic commands ###
