"""empty message

Revision ID: 8d8b8a8a9c0b
Revises: e0248cc6bf14
Create Date: 2018-02-05 11:53:35.718236

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8d8b8a8a9c0b'
down_revision = 'cbdc988a7df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('subfamily', sa.String(length=255), nullable=True),
                    sa.Column('family', sa.String(length=255), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('category_value',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('value', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('association',
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('category_value_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.ForeignKeyConstraint(['category_value_id'], ['category_value.id'], )
                    )

    op.create_table('dimension_category',
        sa.Column('dimension_guid', sa.String(length=255), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('includes_parents', sa.Boolean(), nullable=True),
        sa.Column('includes_all', sa.Boolean(), nullable=True),
        sa.Column('includes_unknown', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
        sa.ForeignKeyConstraint(['dimension_guid'], ['dimension.guid'], ),
        sa.PrimaryKeyConstraint('dimension_guid', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dimension_category')
    op.drop_table('association')
    op.drop_table('category_value')
    op.drop_table('category')
    # ### end Alembic commands ###
