"""empty message

Revision ID: 915fdaf7e1c3
Revises: 62308cd181b2
Create Date: 2020-02-11 10:31:58.122329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "915fdaf7e1c3"
down_revision = "62308cd181b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invalid_user_login_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("ip", sa.String(length=16), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("invalid_user_login_attempt_pkey")),
    )
    op.add_column("users", sa.Column("current_login_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("current_login_ip", sa.String(length=16), nullable=True))
    op.add_column("users", sa.Column("failed_login_count", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("last_login_ip", sa.String(length=16), nullable=True))
    op.add_column("users", sa.Column("login_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "login_count")
    op.drop_column("users", "last_login_ip")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "failed_login_count")
    op.drop_column("users", "current_login_ip")
    op.drop_column("users", "current_login_at")
    op.drop_table("invalid_user_login_attempt")
    # ### end Alembic commands ###
