"""empty message

Revision ID: 9961430bcfea
Revises: 0c148005cc7b
Create Date: 2018-01-19 10:33:25.074402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9961430bcfea'
down_revision = '0c148005cc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequency_of_release',
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('key'),
        sa.UniqueConstraint('description')
    )
    op.get_bind()
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (0, 'monthly', 'Monthly');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (1, 'quarterly', 'Quarterly');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (2, '3-times-a-year', '3 times per year');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (3, 'twice-a-year', 'Twice a year');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (4, 'yearly', 'Yearly');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (5, 'every-2-years', 'Every 2 years');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (6, 'every-3-years', 'Every 3 years');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (7, 'every-4-years', 'Every 4 years');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (8, 'every-5-years', 'Every 5 years');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (9, 'ad-hoc', 'Ad-hoc');")
    op.execute("INSERT INTO frequency_of_release (position, key, description) VALUES (10, 'other', 'Other');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequency_of_release')
    # ### end Alembic commands ###
