"""empty message

Revision ID: 9e714cde1fe0
Revises: 5aba17d3cea1
Create Date: 2017-07-04 15:53:18.826928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e714cde1fe0'
down_revision = '5aba17d3cea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_upload',
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('page_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['db_page.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_upload')
    # ### end Alembic commands ###
