"""empty message

Revision ID: a6d57f7d9ef0
Revises: 25ee89f09e2f
Create Date: 2017-06-26 11:27:37.382205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d57f7d9ef0'
down_revision = '25ee89f09e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_dimension',
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('time_period', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suppression_rules', sa.Text(), nullable=True),
    sa.Column('disclosure_control', sa.Text(), nullable=True),
    sa.Column('type_of_statistic', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.drop_column('db_page', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_page', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('db_dimension')
    # ### end Alembic commands ###
