"""empty message

Revision ID: b032a8a319a5
Revises: 37bdbcac8251
Create Date: 2018-01-22 11:21:07.792431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b032a8a319a5'
down_revision = '37bdbcac8251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequency_of_release',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('description')
    )
    op.add_column('page', sa.Column('frequency_other', sa.String(length=255), nullable=True))

    op.get_bind()
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (0, 'monthly');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (1, 'quarterly');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (2, '3-times-a-year');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (3, 'twice-a-year');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (4, 'yearly');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (5, 'every-2-years');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (6, 'every-3-years');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (7, 'every-4-years');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (8, 'every-5-years');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (9, 'ad-hoc');")
    op.execute("INSERT INTO frequency_of_release (position, description) VALUES (10, 'other');")

    # update existing data
    op.execute("UPDATE page SET frequency = 'monthly' WHERE frequency = 'Monthly';")

    op.execute("UPDATE page SET frequency = '3-times-a-year' WHERE frequency = '3 times a year';")
    op.execute("UPDATE page SET frequency = '3-times-a-year' WHERE frequency = '3 times per year';")

    op.execute("UPDATE page SET frequency = 'quarterly' WHERE frequency = 'Quarterly';")

    op.execute("UPDATE page SET frequency = 'twice-a-year' WHERE frequency = 'Every six months';")
    op.execute("UPDATE page SET frequency = 'twice-a-year' WHERE frequency = 'Every 6 months';")
    op.execute("UPDATE page SET frequency = 'twice-a-year' WHERE frequency = 'Biannual';")

    op.execute("UPDATE page SET frequency = 'ad-hoc' WHERE frequency = 'Ad-hoc';")
    op.execute("UPDATE page SET frequency = 'ad-hoc' WHERE frequency = 'Ad hoc';")

    op.execute("UPDATE page SET frequency = 'yearly' WHERE frequency = 'Annually';")
    op.execute("UPDATE page SET frequency = 'yearly' WHERE frequency = 'Annual';")

    op.execute("UPDATE page SET frequency = 'every-2-years' WHERE frequency = 'Every 2 years';")

    op.execute('''
          UPDATE page SET 
            frequency = 'other', 
            frequency_other = 'Every 7 years (further publications dependent on further surveys being commissioned)'
          WHERE frequency = 'Every 7 years (further publications dependent on further surveys being commissioned)';
          ''')

    op.execute("UPDATE page SET frequency = 'other', frequency_other = 'Term' WHERE frequency = 'Term';")
    op.execute("UPDATE page SET frequency = 'other', frequency_other = 'Every 10 years' WHERE frequency = 'Every 10 years';")
    op.execute("UPDATE page SET frequency = 'other', frequency_other = 'Every 4 to 5 years' WHERE frequency = 'Every 4 to 5 years';")
    op.execute("UPDATE page SET frequency = 'other', frequency_other = 'Every 3 to 4 years' WHERE frequency = 'Every 3 to 4 years';")
    op.execute("UPDATE page SET frequency = 'other', frequency_other = 'Unconfirmed' WHERE frequency = 'Unconfirmed';")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.get_bind()
    op.execute("UPDATE page SET frequency = frequency_other WHERE frequency = 'other';")

    op.drop_column('page', 'frequency_other')
    op.drop_table('frequency_of_release')
    # ### end Alembic commands ###
