"""empty message

Revision ID: c4cd11b9a18f
Revises: 6c3fde4280e0
Create Date: 2018-02-09 13:53:03.503007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cd11b9a18f'
down_revision = '6c3fde4280e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('subfamily', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'subfamily')
    # ### end Alembic commands ###
