"""empty message

Revision ID: c64c6f6fb763
Revises: 8cf04343f0d7
Create Date: 2018-01-24 13:55:33.469453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c64c6f6fb763"
down_revision = "8cf04343f0d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "type_of_statistic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("internal", sa.String(), nullable=False),
        sa.Column("external", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("frequency_of_release", "description", existing_type=sa.VARCHAR(), nullable=False)

    op.add_column("page", sa.Column("type_of_statistic_id", sa.Integer(), nullable=True))
    op.create_foreign_key("type_of_statistic_fkey", "page", "type_of_statistic", ["type_of_statistic_id"], ["id"])

    op.add_column("page", sa.Column("secondary_source_1_type_of_statistic_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "secondary_source_1_type_of_statistic_fkey",
        "page",
        "type_of_statistic",
        ["secondary_source_1_type_of_statistic_id"],
        ["id"],
    )

    op.add_column("page", sa.Column("secondary_source_2_type_of_statistic_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "secondary_source_2_type_of_statistic_fkey",
        "page",
        "type_of_statistic",
        ["secondary_source_2_type_of_statistic_id"],
        ["id"],
    )

    op.get_bind()
    op.execute(
        """
              INSERT INTO type_of_statistic
              (id, internal, external, position)
              VALUES (1, 'National Statistics (certified against a Code of Practice)', 'National Statistics', 1);
              """
    )
    op.execute(
        """
              INSERT INTO type_of_statistic
              (id, internal, external, position)
              VALUES (2, 'Official statistics (any other government statistics)', 'Official statistics', 2);
              """
    )
    op.execute(
        """
              INSERT INTO type_of_statistic
              (id, internal, external, position)
              VALUES (3, 'Experimental statistics', 'Experimental statistics', 3);
              """
    )

    op.execute(
        """
        UPDATE page
        SET type_of_statistic_id = 1
        WHERE type_of_statistic
        IN('National Statistic', 'National statistics', 'National Statstics', 'National statistics', 'National Statistics');
    """
    )

    op.execute("""UPDATE page SET type_of_statistic_id = 2 WHERE type_of_statistic = 'Official statistics';""")

    op.execute(
        """UPDATE page SET secondary_source_1_statistic_type = 3
                  WHERE secondary_source_1_statistic_type = 'Experimental Statistics';"""
    )

    op.execute(
        """UPDATE page SET type_of_statistic_id = NULL
                  WHERE trim(type_of_statistic) = '';"""
    )

    op.execute(
        """UPDATE page
                  SET secondary_source_1_type_of_statistic_id = NULL
                  WHERE trim(secondary_source_1_statistic_type) = '';
    """
    )

    op.execute(
        """UPDATE page
                  SET secondary_source_1_type_of_statistic_id = 2
                  WHERE secondary_source_1_statistic_type = 'Official statistic'
    """
    )

    op.execute(
        """UPDATE page
                  SET secondary_source_1_type_of_statistic_id = NULL
                  WHERE trim(secondary_source_1_statistic_type) = '';"""
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("type_of_statistic_fkey", "page", type_="foreignkey")
    op.drop_constraint("secondary_source_1_type_of_statistic_fkey", "page", type_="foreignkey")
    op.drop_constraint("secondary_source_2_type_of_statistic_fkey", "page", type_="foreignkey")

    op.drop_column("page", "type_of_statistic_id")
    op.drop_column("page", "secondary_source_2_type_of_statistic_id")
    op.drop_column("page", "secondary_source_1_type_of_statistic_id")

    op.alter_column("frequency_of_release", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("type_of_statistic")
    # ### end Alembic commands ###
