"""empty message

Revision ID: dab42c0a0f0d
Revises: 25ee89f09e2f
Create Date: 2017-06-29 18:52:08.668165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dab42c0a0f0d'
down_revision = '25ee89f09e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_dimension',
    sa.Column('guid', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('time_period', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suppression_rules', sa.Text(), nullable=True),
    sa.Column('disclosure_control', sa.Text(), nullable=True),
    sa.Column('type_of_statistic', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('chart', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('table', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('chart_source_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('table_source_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('measure_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['db_page.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )

    op.alter_column('db_page', 'description', type_=sa.Text)
    op.execute('COMMIT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_dimension')
    # ### end Alembic commands ###
