"""empty message

Revision ID: dbd7ae1b41a8
Revises: 6ec31fd4ac57
Create Date: 2018-02-14 14:35:28.968358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd7ae1b41a8'
down_revision = '6ec31fd4ac57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('review_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'review_token')
    # ### end Alembic commands ###
