"""empty message

Revision ID: e553b195fe90
Revises:
Create Date: 2017-07-19 12:00:20.474429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e553b195fe90"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(length=255), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "db_page",
        sa.Column("guid", sa.String(length=255), nullable=False),
        sa.Column("uri", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("page_type", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("published", sa.BOOLEAN(), nullable=True),
        sa.Column("parent_guid", sa.String(length=255), nullable=True),
        sa.Column("page_json", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("measure_summary", sa.TEXT(), nullable=True),
        sa.Column("summary", sa.TEXT(), nullable=True),
        sa.Column("geographic_coverage", sa.TEXT(), nullable=True),
        sa.Column("lowest_level_of_geography", sa.TEXT(), nullable=True),
        sa.Column("time_covered", sa.String(length=255), nullable=True),
        sa.Column("need_to_know", sa.TEXT(), nullable=True),
        sa.Column("ethnicity_definition_summary", sa.TEXT(), nullable=True),
        sa.Column("ethnicity_definition_detail", sa.TEXT(), nullable=True),
        sa.Column("source_text", sa.TEXT(), nullable=True),
        sa.Column("source_url", sa.TEXT(), nullable=True),
        sa.Column("department_source", sa.TEXT(), nullable=True),
        sa.Column("published_date", sa.String(length=255), nullable=True),
        sa.Column("last_update_date", sa.String(length=255), nullable=True),
        sa.Column("next_update_date", sa.String(length=255), nullable=True),
        sa.Column("frequency", sa.String(length=255), nullable=True),
        sa.Column("related_publications", sa.TEXT(), nullable=True),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=255), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("data_source_purpose", sa.TEXT(), nullable=True),
        sa.Column("methodology", sa.TEXT(), nullable=True),
        sa.Column("data_type", sa.String(length=255), nullable=True),
        sa.Column("suppression_rules", sa.TEXT(), nullable=True),
        sa.Column("disclosure_control", sa.TEXT(), nullable=True),
        sa.Column("estimation", sa.TEXT(), nullable=True),
        sa.Column("type_of_statistic", sa.String(length=255), nullable=True),
        sa.Column("qmi_url", sa.TEXT(), nullable=True),
        sa.Column("further_technical_information", sa.TEXT(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("subtopics", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(["parent_guid"], ["db_page.guid"],),
        sa.PrimaryKeyConstraint("guid"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="users_email_key"),
    )
    op.create_table(
        "db_dimension",
        sa.Column("guid", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("time_period", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("suppression_rules", sa.Text(), nullable=True),
        sa.Column("disclosure_control", sa.Text(), nullable=True),
        sa.Column("type_of_statistic", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("chart", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("table", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("chart_source_data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("table_source_data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("measure_id", sa.String(length=255), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["measure_id"], ["db_page.guid"],),
        sa.PrimaryKeyConstraint("guid"),
    )
    op.create_table(
        "db_upload",
        sa.Column("guid", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("page_id", sa.String(length=255), nullable=True),
        sa.Column("size", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["page_id"], ["db_page.guid"],),
        sa.PrimaryKeyConstraint("guid"),
    )
    op.create_table(
        "roles_users",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_users")
    op.drop_table("db_upload")
    op.drop_table("db_dimension")
    op.drop_table("users")
    op.drop_table("role")
    op.drop_table("db_page")
    op.drop_table("audit")
    # ### end Alembic commands ###
