"""empty message

Revision ID: e65a9ec3b836
Revises: b73de66d0469
Create Date: 2017-10-05 14:32:50.509441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e65a9ec3b836"
down_revision = "b73de66d0469"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("db_page", sa.Column("position", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("db_page", "position")
    # ### end Alembic commands ###
