"""empty message

Revision ID: e722179fb7a8
Revises: eb0fa941c034
Create Date: 2017-10-31 10:31:06.978360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e722179fb7a8"
down_revision = "eb0fa941c034"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("db_page", sa.Column("db_version_id", sa.Integer()))
    op.execute("UPDATE db_page SET db_version_id = 1;")
    op.alter_column("db_page", "db_version_id", existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("db_page", "db_version_id")
    # ### end Alembic commands ###
