"""empty message

Revision ID: eb0fa941c034
Revises: 120c0d4099da
Create Date: 2017-10-26 21:39:22.193451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb0fa941c034"
down_revision = "120c0d4099da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("confirmed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed_at")
    # ### end Alembic commands ###
