"""empty message

Revision ID: f5b48cf7f118
Revises: 99062ef6b9dc
Create Date: 2017-09-29 13:58:16.231967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

from application.cms.models import DbPage

revision = 'f5b48cf7f118'
down_revision = '99062ef6b9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    session = Session(bind=op.get_bind())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dimension', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('db_dimension', sa.Column('suppression_rules', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('db_dimension', sa.Column('disclosure_control', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('db_dimension', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('db_dimension', sa.Column('type_of_statistic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
