"""empty message

Revision ID: fd5178b68fe6
Revises: 334faaf60a3d
Create Date: 2017-06-26 14:44:18.464089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5178b68fe6'
down_revision = '334faaf60a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dimension', sa.Column('chart', sa.Text(), nullable=True))
    op.add_column('db_dimension', sa.Column('table', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_dimension', 'table')
    op.drop_column('db_dimension', 'chart')
    # ### end Alembic commands ###
